const gameType = {
  1: 'Main game',
  2: 'Corners',
  3: 'Double',
  4: 'Aces',
  6: 'Removal',
  7: 'Penalty time',
  8: 'Yellow cards',
  10: 'Cards',
  11: 'Misses',
  12: 'Shots on target',
  13: 'Offside',
  14: 'Fouls',
  15: 'Shots on goal',
  16: 'Additional rates',
  17: 'Game series',
  18: 'Free throws scored',
  19: 'Scored two-point shots',
  20: 'Scored three-point shots',
  21: 'Rebounds',
  22: 'Assists',
  23: 'Turnovers',
  24: 'Blocks',
  26: 'Double errors',
  27: 'Posts and Crossbars',
  28: 'Breaks',
  29: 'Ball ownership percentage',
  30: 'Replacements',
  31: '1 game',
  32: '2 game',
  33: 'Shootouts',
  34: 'Hits',
  35: 'Intercepts',
  36: 'Defensive rebound',
  37: 'Offensive rebound',
  38: 'Extra bullets',
  39: 'Best by sets',
  40: 'Alternative outcomes',
  41: 'Express outcomes',
  42: 'Cards. statistics',
  10000: 'Maps',
  10001: 'Rounds',
  10002: 'Frags',
}

export type GameTypeId = keyof typeof gameType

export default gameType
