/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace ICore {
  export type ConditionStruct = {
    fundBank: [BigNumberish, BigNumberish];
    payouts: [BigNumberish, BigNumberish];
    totalNetBets: [BigNumberish, BigNumberish];
    reinforcement: BigNumberish;
    margin: BigNumberish;
    outcomes: [BigNumberish, BigNumberish];
    ipfsHash: BytesLike;
    scopeID: BigNumberish;
    outcomeWin: BigNumberish;
    timestamp: BigNumberish;
    state: BigNumberish;
  };

  export type ConditionStructOutput = [
    [BigNumber, BigNumber],
    [BigNumber, BigNumber],
    [BigNumber, BigNumber],
    BigNumber,
    BigNumber,
    [BigNumber, BigNumber],
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    number
  ] & {
    fundBank: [BigNumber, BigNumber];
    payouts: [BigNumber, BigNumber];
    totalNetBets: [BigNumber, BigNumber];
    reinforcement: BigNumber;
    margin: BigNumber;
    outcomes: [BigNumber, BigNumber];
    ipfsHash: string;
    scopeID: BigNumber;
    outcomeWin: BigNumber;
    timestamp: BigNumber;
    state: number;
  };
}

export interface CoreInterface extends utils.Interface {
  contractName: "Core";
  functions: {
    "addMaintainer(address,bool)": FunctionFragment;
    "addMargin(uint256,uint256,uint256)": FunctionFragment;
    "allConditionStopped()": FunctionFragment;
    "bets(uint256)": FunctionFragment;
    "calculateOdds(uint256,uint128,uint64)": FunctionFragment;
    "cancel(uint256)": FunctionFragment;
    "cancelByMaintainer(uint256)": FunctionFragment;
    "ceil(uint256,uint256,uint256)": FunctionFragment;
    "changeMaxBanksRatio(uint64)": FunctionFragment;
    "conditions(uint256)": FunctionFragment;
    "createCondition(uint256,uint128,uint64[2],uint64[2],uint64,bytes32)": FunctionFragment;
    "decimals()": FunctionFragment;
    "defaultMargin()": FunctionFragment;
    "defaultReinforcement()": FunctionFragment;
    "getBetInfo(uint256)": FunctionFragment;
    "getCondition(uint256)": FunctionFragment;
    "getConditionFunds(uint256)": FunctionFragment;
    "getConditionReinforcement(uint256)": FunctionFragment;
    "getLockedPayout()": FunctionFragment;
    "getMargin(uint64)": FunctionFragment;
    "getOddsFromBanks(uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "getReinforcement(uint64)": FunctionFragment;
    "initialize(uint128,address,uint128)": FunctionFragment;
    "isOracle(address)": FunctionFragment;
    "isOutComeCorrect(uint256,uint256)": FunctionFragment;
    "lastConditionId()": FunctionFragment;
    "lpAddress()": FunctionFragment;
    "maintainers(address)": FunctionFragment;
    "maxBanksRatio()": FunctionFragment;
    "oracleConditionIDs(address,uint256)": FunctionFragment;
    "oracles(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "putBet(uint256,uint256,uint128,uint64,uint64,address)": FunctionFragment;
    "renounceOracle(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "resolveCondition(uint256,uint64)": FunctionFragment;
    "resolvePayout(uint256)": FunctionFragment;
    "setLP(address)": FunctionFragment;
    "setOracle(address)": FunctionFragment;
    "shift(uint256,uint64)": FunctionFragment;
    "sqrt(uint256)": FunctionFragment;
    "stopAllConditions(bool)": FunctionFragment;
    "stopCondition(uint256,bool)": FunctionFragment;
    "totalLockedPayout()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateMargins(uint128[])": FunctionFragment;
    "updateReinforcements(uint128[])": FunctionFragment;
    "viewPayout(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addMaintainer",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "addMargin",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allConditionStopped",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bets", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "calculateOdds",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelByMaintainer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ceil",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeMaxBanksRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "conditions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCondition",
    values: [
      BigNumberish,
      BigNumberish,
      [BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish],
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultMargin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultReinforcement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBetInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCondition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConditionFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConditionReinforcement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockedPayout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMargin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOddsFromBanks",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getReinforcement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isOracle", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isOutComeCorrect",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastConditionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpAddress", values?: undefined): string;
  encodeFunctionData(functionFragment: "maintainers", values: [string]): string;
  encodeFunctionData(
    functionFragment: "maxBanksRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleConditionIDs",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracles", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "putBet",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveCondition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolvePayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setLP", values: [string]): string;
  encodeFunctionData(functionFragment: "setOracle", values: [string]): string;
  encodeFunctionData(
    functionFragment: "shift",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sqrt", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stopAllConditions",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stopCondition",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLockedPayout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMargins",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReinforcements",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "viewPayout",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addMaintainer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMargin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allConditionStopped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateOdds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelByMaintainer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ceil", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeMaxBanksRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "conditions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultReinforcement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBetInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditionFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditionReinforcement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockedPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMargin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOddsFromBanks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReinforcement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isOutComeCorrect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastConditionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maintainers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxBanksRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleConditionIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "putBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolvePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shift", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sqrt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stopAllConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLockedPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMargins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReinforcements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "viewPayout", data: BytesLike): Result;

  events: {
    "ConditionCreated(uint256,uint256,uint64)": EventFragment;
    "ConditionResolved(uint256,uint256,uint64,uint8,uint256)": EventFragment;
    "ConditionShifted(uint256,uint64)": EventFragment;
    "LPChanged(address)": EventFragment;
    "MaintainerUpdated(address,bool)": EventFragment;
    "OracleAdded(address)": EventFragment;
    "OracleRenounced(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "allConditionsStoped(bool)": EventFragment;
    "conditionStoped(uint256,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConditionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConditionResolved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConditionShifted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LPChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaintainerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OracleAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OracleRenounced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "allConditionsStoped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "conditionStoped"): EventFragment;
}

export type ConditionCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  { oracleConditionID: BigNumber; conditionID: BigNumber; timestamp: BigNumber }
>;

export type ConditionCreatedEventFilter =
  TypedEventFilter<ConditionCreatedEvent>;

export type ConditionResolvedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, number, BigNumber],
  {
    oracleConditionID: BigNumber;
    conditionID: BigNumber;
    outcomeWin: BigNumber;
    state: number;
    amountForLP: BigNumber;
  }
>;

export type ConditionResolvedEventFilter =
  TypedEventFilter<ConditionResolvedEvent>;

export type ConditionShiftedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { conditionID: BigNumber; newTimestamp: BigNumber }
>;

export type ConditionShiftedEventFilter =
  TypedEventFilter<ConditionShiftedEvent>;

export type LPChangedEvent = TypedEvent<[string], { newLP: string }>;

export type LPChangedEventFilter = TypedEventFilter<LPChangedEvent>;

export type MaintainerUpdatedEvent = TypedEvent<
  [string, boolean],
  { maintainer: string; active: boolean }
>;

export type MaintainerUpdatedEventFilter =
  TypedEventFilter<MaintainerUpdatedEvent>;

export type OracleAddedEvent = TypedEvent<[string], { newOracle: string }>;

export type OracleAddedEventFilter = TypedEventFilter<OracleAddedEvent>;

export type OracleRenouncedEvent = TypedEvent<[string], { oracle: string }>;

export type OracleRenouncedEventFilter = TypedEventFilter<OracleRenouncedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type allConditionsStopedEvent = TypedEvent<[boolean], { flag: boolean }>;

export type allConditionsStopedEventFilter =
  TypedEventFilter<allConditionsStopedEvent>;

export type conditionStopedEvent = TypedEvent<
  [BigNumber, boolean],
  { conditionID: BigNumber; flag: boolean }
>;

export type conditionStopedEventFilter = TypedEventFilter<conditionStopedEvent>;

export interface Core extends BaseContract {
  contractName: "Core";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addMaintainer(
      maintainer: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addMargin(
      odds: BigNumberish,
      marginality: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { newOdds: BigNumber }>;

    allConditionStopped(overrides?: CallOverrides): Promise<[boolean]>;

    bets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        boolean
      ] & {
        conditionID: BigNumber;
        amount: BigNumber;
        outcome: BigNumber;
        createdAt: BigNumber;
        affiliate: string;
        odds: BigNumber;
        payed: boolean;
      }
    >;

    calculateOdds(
      conditionID: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { odds: BigNumber }>;

    cancel(
      oracleConditionID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelByMaintainer(
      conditionID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ceil(
      a: BigNumberish,
      m: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    changeMaxBanksRatio(
      newRatio_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        reinforcement: BigNumber;
        margin: BigNumber;
        ipfsHash: string;
        scopeID: BigNumber;
        outcomeWin: BigNumber;
        timestamp: BigNumber;
        state: number;
      }
    >;

    createCondition(
      oracleCondID: BigNumberish,
      scopeID: BigNumberish,
      odds: [BigNumberish, BigNumberish],
      outcomes: [BigNumberish, BigNumberish],
      timestamp: BigNumberish,
      ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decimals(overrides?: CallOverrides): Promise<[BigNumber]>;

    defaultMargin(overrides?: CallOverrides): Promise<[BigNumber]>;

    defaultReinforcement(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBetInfo(
      betId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string] & {
        amount: BigNumber;
        odds: BigNumber;
        createdAt: BigNumber;
        affiliate: string;
      }
    >;

    getCondition(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[ICore.ConditionStructOutput]>;

    getConditionFunds(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber]] & { fundBank: [BigNumber, BigNumber] }>;

    getConditionReinforcement(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { reinforcement: BigNumber }>;

    getLockedPayout(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMargin(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getOddsFromBanks(
      fund1Bank_: BigNumberish,
      fund2Bank_: BigNumberish,
      amount_: BigNumberish,
      outcomeIndex_: BigNumberish,
      marginality_: BigNumberish,
      decimals_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getReinforcement(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initialize(
      reinforcement_: BigNumberish,
      oracle_: string,
      margin_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isOracle(
      oracleWallet: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isOutComeCorrect(
      conditionID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { correct: boolean }>;

    lastConditionId(overrides?: CallOverrides): Promise<[BigNumber]>;

    lpAddress(overrides?: CallOverrides): Promise<[string]>;

    maintainers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    maxBanksRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    oracleConditionIDs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    oracles(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    putBet(
      conditionID: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      minOdds: BigNumberish,
      affiliate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resolveCondition(
      oracleCondID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resolvePayout(
      tokenID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLP(
      lpAddress_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    shift(
      conditionID: BigNumberish,
      newTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sqrt(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { y: BigNumber }>;

    stopAllConditions(
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopCondition(
      conditionID: BigNumberish,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalLockedPayout(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateMargins(
      data_: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateReinforcements(
      data_: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    viewPayout(
      tokenID_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { success: boolean; amount: BigNumber }>;
  };

  addMaintainer(
    maintainer: string,
    active: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addMargin(
    odds: BigNumberish,
    marginality: BigNumberish,
    decimals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  allConditionStopped(overrides?: CallOverrides): Promise<boolean>;

  bets(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, string, BigNumber, boolean] & {
      conditionID: BigNumber;
      amount: BigNumber;
      outcome: BigNumber;
      createdAt: BigNumber;
      affiliate: string;
      odds: BigNumber;
      payed: boolean;
    }
  >;

  calculateOdds(
    conditionID: BigNumberish,
    amount: BigNumberish,
    outcomeWin: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancel(
    oracleConditionID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelByMaintainer(
    conditionID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ceil(
    a: BigNumberish,
    m: BigNumberish,
    decimals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  changeMaxBanksRatio(
    newRatio_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  conditions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, BigNumber, BigNumber, BigNumber, number] & {
      reinforcement: BigNumber;
      margin: BigNumber;
      ipfsHash: string;
      scopeID: BigNumber;
      outcomeWin: BigNumber;
      timestamp: BigNumber;
      state: number;
    }
  >;

  createCondition(
    oracleCondID: BigNumberish,
    scopeID: BigNumberish,
    odds: [BigNumberish, BigNumberish],
    outcomes: [BigNumberish, BigNumberish],
    timestamp: BigNumberish,
    ipfsHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decimals(overrides?: CallOverrides): Promise<BigNumber>;

  defaultMargin(overrides?: CallOverrides): Promise<BigNumber>;

  defaultReinforcement(overrides?: CallOverrides): Promise<BigNumber>;

  getBetInfo(
    betId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, string] & {
      amount: BigNumber;
      odds: BigNumber;
      createdAt: BigNumber;
      affiliate: string;
    }
  >;

  getCondition(
    conditionID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ICore.ConditionStructOutput>;

  getConditionFunds(
    conditionID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getConditionReinforcement(
    conditionID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLockedPayout(overrides?: CallOverrides): Promise<BigNumber>;

  getMargin(
    outcomeId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOddsFromBanks(
    fund1Bank_: BigNumberish,
    fund2Bank_: BigNumberish,
    amount_: BigNumberish,
    outcomeIndex_: BigNumberish,
    marginality_: BigNumberish,
    decimals_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getReinforcement(
    outcomeId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initialize(
    reinforcement_: BigNumberish,
    oracle_: string,
    margin_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isOracle(oracleWallet: string, overrides?: CallOverrides): Promise<boolean>;

  isOutComeCorrect(
    conditionID: BigNumberish,
    outcomeWin: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lastConditionId(overrides?: CallOverrides): Promise<BigNumber>;

  lpAddress(overrides?: CallOverrides): Promise<string>;

  maintainers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  maxBanksRatio(overrides?: CallOverrides): Promise<BigNumber>;

  oracleConditionIDs(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  oracles(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  putBet(
    conditionID: BigNumberish,
    tokenId: BigNumberish,
    amount: BigNumberish,
    outcomeWin: BigNumberish,
    minOdds: BigNumberish,
    affiliate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOracle(
    oracle_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resolveCondition(
    oracleCondID: BigNumberish,
    outcomeWin: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resolvePayout(
    tokenID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLP(
    lpAddress_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOracle(
    oracle_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  shift(
    conditionID: BigNumberish,
    newTimestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sqrt(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  stopAllConditions(
    flag: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopCondition(
    conditionID: BigNumberish,
    flag: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalLockedPayout(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateMargins(
    data_: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateReinforcements(
    data_: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  viewPayout(
    tokenID_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { success: boolean; amount: BigNumber }>;

  callStatic: {
    addMaintainer(
      maintainer: string,
      active: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    addMargin(
      odds: BigNumberish,
      marginality: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allConditionStopped(overrides?: CallOverrides): Promise<boolean>;

    bets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        boolean
      ] & {
        conditionID: BigNumber;
        amount: BigNumber;
        outcome: BigNumber;
        createdAt: BigNumber;
        affiliate: string;
        odds: BigNumber;
        payed: boolean;
      }
    >;

    calculateOdds(
      conditionID: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancel(
      oracleConditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelByMaintainer(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ceil(
      a: BigNumberish,
      m: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeMaxBanksRatio(
      newRatio_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        reinforcement: BigNumber;
        margin: BigNumber;
        ipfsHash: string;
        scopeID: BigNumber;
        outcomeWin: BigNumber;
        timestamp: BigNumber;
        state: number;
      }
    >;

    createCondition(
      oracleCondID: BigNumberish,
      scopeID: BigNumberish,
      odds: [BigNumberish, BigNumberish],
      outcomes: [BigNumberish, BigNumberish],
      timestamp: BigNumberish,
      ipfsHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    defaultMargin(overrides?: CallOverrides): Promise<BigNumber>;

    defaultReinforcement(overrides?: CallOverrides): Promise<BigNumber>;

    getBetInfo(
      betId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string] & {
        amount: BigNumber;
        odds: BigNumber;
        createdAt: BigNumber;
        affiliate: string;
      }
    >;

    getCondition(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ICore.ConditionStructOutput>;

    getConditionFunds(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getConditionReinforcement(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLockedPayout(overrides?: CallOverrides): Promise<BigNumber>;

    getMargin(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOddsFromBanks(
      fund1Bank_: BigNumberish,
      fund2Bank_: BigNumberish,
      amount_: BigNumberish,
      outcomeIndex_: BigNumberish,
      marginality_: BigNumberish,
      decimals_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReinforcement(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      reinforcement_: BigNumberish,
      oracle_: string,
      margin_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    isOracle(oracleWallet: string, overrides?: CallOverrides): Promise<boolean>;

    isOutComeCorrect(
      conditionID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lastConditionId(overrides?: CallOverrides): Promise<BigNumber>;

    lpAddress(overrides?: CallOverrides): Promise<string>;

    maintainers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    maxBanksRatio(overrides?: CallOverrides): Promise<BigNumber>;

    oracleConditionIDs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracles(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    putBet(
      conditionID: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      minOdds: BigNumberish,
      affiliate: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    renounceOracle(oracle_: string, overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    resolveCondition(
      oracleCondID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    resolvePayout(
      tokenID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { success: boolean; amount: BigNumber }>;

    setLP(lpAddress_: string, overrides?: CallOverrides): Promise<void>;

    setOracle(oracle_: string, overrides?: CallOverrides): Promise<void>;

    shift(
      conditionID: BigNumberish,
      newTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sqrt(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    stopAllConditions(flag: boolean, overrides?: CallOverrides): Promise<void>;

    stopCondition(
      conditionID: BigNumberish,
      flag: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    totalLockedPayout(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMargins(
      data_: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    updateReinforcements(
      data_: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    viewPayout(
      tokenID_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { success: boolean; amount: BigNumber }>;
  };

  filters: {
    "ConditionCreated(uint256,uint256,uint64)"(
      oracleConditionID?: BigNumberish | null,
      conditionID?: BigNumberish | null,
      timestamp?: null
    ): ConditionCreatedEventFilter;
    ConditionCreated(
      oracleConditionID?: BigNumberish | null,
      conditionID?: BigNumberish | null,
      timestamp?: null
    ): ConditionCreatedEventFilter;

    "ConditionResolved(uint256,uint256,uint64,uint8,uint256)"(
      oracleConditionID?: BigNumberish | null,
      conditionID?: BigNumberish | null,
      outcomeWin?: null,
      state?: null,
      amountForLP?: null
    ): ConditionResolvedEventFilter;
    ConditionResolved(
      oracleConditionID?: BigNumberish | null,
      conditionID?: BigNumberish | null,
      outcomeWin?: null,
      state?: null,
      amountForLP?: null
    ): ConditionResolvedEventFilter;

    "ConditionShifted(uint256,uint64)"(
      conditionID?: null,
      newTimestamp?: null
    ): ConditionShiftedEventFilter;
    ConditionShifted(
      conditionID?: null,
      newTimestamp?: null
    ): ConditionShiftedEventFilter;

    "LPChanged(address)"(newLP?: string | null): LPChangedEventFilter;
    LPChanged(newLP?: string | null): LPChangedEventFilter;

    "MaintainerUpdated(address,bool)"(
      maintainer?: string | null,
      active?: null
    ): MaintainerUpdatedEventFilter;
    MaintainerUpdated(
      maintainer?: string | null,
      active?: null
    ): MaintainerUpdatedEventFilter;

    "OracleAdded(address)"(newOracle?: string | null): OracleAddedEventFilter;
    OracleAdded(newOracle?: string | null): OracleAddedEventFilter;

    "OracleRenounced(address)"(
      oracle?: string | null
    ): OracleRenouncedEventFilter;
    OracleRenounced(oracle?: string | null): OracleRenouncedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "allConditionsStoped(bool)"(flag?: null): allConditionsStopedEventFilter;
    allConditionsStoped(flag?: null): allConditionsStopedEventFilter;

    "conditionStoped(uint256,bool)"(
      conditionID?: BigNumberish | null,
      flag?: null
    ): conditionStopedEventFilter;
    conditionStoped(
      conditionID?: BigNumberish | null,
      flag?: null
    ): conditionStopedEventFilter;
  };

  estimateGas: {
    addMaintainer(
      maintainer: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addMargin(
      odds: BigNumberish,
      marginality: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allConditionStopped(overrides?: CallOverrides): Promise<BigNumber>;

    bets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    calculateOdds(
      conditionID: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancel(
      oracleConditionID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelByMaintainer(
      conditionID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ceil(
      a: BigNumberish,
      m: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeMaxBanksRatio(
      newRatio_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createCondition(
      oracleCondID: BigNumberish,
      scopeID: BigNumberish,
      odds: [BigNumberish, BigNumberish],
      outcomes: [BigNumberish, BigNumberish],
      timestamp: BigNumberish,
      ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    defaultMargin(overrides?: CallOverrides): Promise<BigNumber>;

    defaultReinforcement(overrides?: CallOverrides): Promise<BigNumber>;

    getBetInfo(
      betId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCondition(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConditionFunds(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConditionReinforcement(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLockedPayout(overrides?: CallOverrides): Promise<BigNumber>;

    getMargin(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOddsFromBanks(
      fund1Bank_: BigNumberish,
      fund2Bank_: BigNumberish,
      amount_: BigNumberish,
      outcomeIndex_: BigNumberish,
      marginality_: BigNumberish,
      decimals_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReinforcement(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      reinforcement_: BigNumberish,
      oracle_: string,
      margin_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isOracle(
      oracleWallet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOutComeCorrect(
      conditionID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastConditionId(overrides?: CallOverrides): Promise<BigNumber>;

    lpAddress(overrides?: CallOverrides): Promise<BigNumber>;

    maintainers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    maxBanksRatio(overrides?: CallOverrides): Promise<BigNumber>;

    oracleConditionIDs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracles(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    putBet(
      conditionID: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      minOdds: BigNumberish,
      affiliate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resolveCondition(
      oracleCondID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resolvePayout(
      tokenID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLP(
      lpAddress_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    shift(
      conditionID: BigNumberish,
      newTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sqrt(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    stopAllConditions(
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopCondition(
      conditionID: BigNumberish,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalLockedPayout(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateMargins(
      data_: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateReinforcements(
      data_: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    viewPayout(
      tokenID_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addMaintainer(
      maintainer: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addMargin(
      odds: BigNumberish,
      marginality: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allConditionStopped(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateOdds(
      conditionID: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancel(
      oracleConditionID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelByMaintainer(
      conditionID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ceil(
      a: BigNumberish,
      m: BigNumberish,
      decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeMaxBanksRatio(
      newRatio_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    conditions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createCondition(
      oracleCondID: BigNumberish,
      scopeID: BigNumberish,
      odds: [BigNumberish, BigNumberish],
      outcomes: [BigNumberish, BigNumberish],
      timestamp: BigNumberish,
      ipfsHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultMargin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultReinforcement(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBetInfo(
      betId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCondition(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConditionFunds(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConditionReinforcement(
      conditionID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLockedPayout(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMargin(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOddsFromBanks(
      fund1Bank_: BigNumberish,
      fund2Bank_: BigNumberish,
      amount_: BigNumberish,
      outcomeIndex_: BigNumberish,
      marginality_: BigNumberish,
      decimals_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReinforcement(
      outcomeId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      reinforcement_: BigNumberish,
      oracle_: string,
      margin_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isOracle(
      oracleWallet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOutComeCorrect(
      conditionID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastConditionId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lpAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maintainers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxBanksRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oracleConditionIDs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracles(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    putBet(
      conditionID: BigNumberish,
      tokenId: BigNumberish,
      amount: BigNumberish,
      outcomeWin: BigNumberish,
      minOdds: BigNumberish,
      affiliate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resolveCondition(
      oracleCondID: BigNumberish,
      outcomeWin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resolvePayout(
      tokenID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLP(
      lpAddress_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOracle(
      oracle_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    shift(
      conditionID: BigNumberish,
      newTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sqrt(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stopAllConditions(
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopCondition(
      conditionID: BigNumberish,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalLockedPayout(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateMargins(
      data_: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateReinforcements(
      data_: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    viewPayout(
      tokenID_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
